name: Run Selenium Scraper

on:
  schedule:
    - cron: '0 16 * * *'  # Runs every 24 hours at midnight UTC (8 AM Shanghai)
  workflow_dispatch:  # Allows manual execution

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Firefox via apt
        run: |
          sudo add-apt-repository -y ppa:mozillateam/ppa
          echo 'Package: *' | sudo tee /etc/apt/preferences.d/mozillateam
          echo 'Pin: release o=LP-PPA-mozillateam' | sudo tee -a /etc/apt/preferences.d/mozillateam
          echo 'Pin-Priority: 1001' | sudo tee -a /etc/apt/preferences.d/mozillateam
          sudo apt update
          sudo apt install -y firefox

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Selenium scraper
        run: python opus_scraper.py

      - name: Commit and push updates
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add dynamics.txt
          git commit -m "Auto-update dynamics.txt with latest post" || echo "No changes to commit"
          git push
